/*
  RESUMO DA LÓGICA DO BANCO DE DADOS - SISTEMA DE MONITORAMENTO DE ATIVIDADE FÍSICA

  1. GESTÃO DE USUÁRIOS E PERFIS:
     - Suporta PACIENTES e ADMINISTRADORES. Pacientes possuem perfis detalhados com informações 
       clínicas (tipo de artrite, tempo de diagnóstico).

  2. TRIAGEM E EVOLUÇÃO (sessoes_triagem):
     - Registra scores de diversos instrumentos (IPAQ, FACIT-F, etc.) em fases iniciais e finais
       para mensurar o impacto das intervenções.

  3. HIERARQUIA DE MONITORAMENTO:
     - Relatório Semanal: Agregador principal que consolida o desempenho de uma semana.
     - Relatório Diário: Vinculado a uma semana, registra métricas subjetivas (dor e fadiga).
     - Registro de Atividade: Atividades específicas realizadas no dia, vinculadas ao relatório diário.

  4. LÓGICA DE CÁLCULO E PONTUAÇÃO:
     - MET (Metabolic Equivalent of Task): Calculado com base no valor de referência da atividade
       cadastrada vs. a duração informada pelo usuário.
     - PONTUAÇÃO: Sistema de pesos por intensidade para gamificação/metas:
       (Minutos Leves * 1) + (Minutos Moderados * 2) + (Minutos Intensos * 3).

  5. REGRAS DE NEGÓCIO:
     - Prazo de Edição: Centralizado na função 'prazo_edicao_config', limitando alterações 
       retroativas (ex: 72h) para garantir a integridade dos dados coletados.
*/

CREATE TYPE "papel_usuario" AS ENUM (
  'PACIENTE',
  'ADMINISTRADOR'
);

CREATE TYPE "fase_triagem" AS ENUM (
  'INICIAL',
  'FINAL'
);

CREATE TYPE "intensidade_atividade" AS ENUM (
  'LEVE',
  'MODERADO',
  'INTENSO'
);

CREATE TYPE "turno_dia" AS ENUM (
  'MANHA',
  'TARDE',
  'NOITE'
);

-- Função para centralizar o prazo de edição (atua como uma variável global)
CREATE OR REPLACE FUNCTION prazo_edicao_config() RETURNS interval AS $$
BEGIN
  RETURN interval '72 hours';
END;
$$ LANGUAGE plpgsql;

CREATE TABLE "usuarios" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "telefone" TEXT NOT NULL,
  "data_nascimento" DATE NOT NULL,
  "senha_hash" TEXT,
  "google_id" TEXT UNIQUE,
  "papel" papel_usuario NOT NULL DEFAULT 'PACIENTE',
  "email_verificado" Boolean NOT NULL DEFAULT false,
  "lgpd_aceita_em" TIMESTAMP,
  "consentimento_saude_em" TIMESTAMP,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "perfis_paciente" (
  "id_perfil_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int UNIQUE NOT NULL,
  "sexo" TEXT NOT NULL,
  "escolaridade" TEXT NOT NULL,
  "raca_cor" TEXT NOT NULL,
  "estado_civil" TEXT NOT NULL,
  "tipo_artrite_id" Int NOT NULL,
  "tempo_tratamento_meses" Int,
  "tempo_diagnostico_meses" Int,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "tipos_artrite" (
  "id_tipo_artrite" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT UNIQUE NOT NULL,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "sessoes_triagem" (
  "id_sessao_triagem" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "fase" fase_triagem NOT NULL,
  "score_ipaq" Decimal,
  "score_facit_f" Decimal,
  "score_pam13" Decimal,
  "score_sam" Decimal,
  "score_sure" Decimal,
  "score_umars" Decimal,
  "score_eheals" Decimal,
  "eva_inicial" Int,
  "respostas_brutas" Json,
  "concluida_em" TIMESTAMP,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "ativa" Boolean NOT NULL DEFAULT true
);

CREATE TABLE "atividades_cadastradas" (
  "id_atividade_cadastrada" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "categoria" TEXT, -- Agrupamento opcional (ex: Lazer, Trabalho)
  "MET_leve" FLOAT NOT NULL DEFAULT 0.0,
  "MET_moderado" FLOAT NOT NULL DEFAULT 0.0,
  "MET_intenso" FLOAT NOT NULL DEFAULT 0.0,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "relatorios_semanais" (
  "id_relatorio_semanal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "data_inicio_semana" TIMESTAMP NOT NULL,
  "data_fim_semana" TIMESTAMP NOT NULL,
  -- "minutos_totais" Int NOT NULL DEFAULT 0, -- tirei pq é um atributo que se pode derivar dos outros 3 de baixo
  "minutos_leve" Int NOT NULL DEFAULT 0,
  "minutos_moderado" Int NOT NULL DEFAULT 0,
  "minutos_intenso" Int NOT NULL DEFAULT 0,
  "pontuacao" Int NOT NULL DEFAULT 0, -- Calculado como: (minutos_leve * 1) + (minutos_moderado * 2) + (minutos_intenso * 3)
  "met_total" Decimal NOT NULL DEFAULT 0,
  "meta_atingida" Boolean NOT NULL DEFAULT false,
  "editavel_ate" TIMESTAMP NOT NULL, -- Calculado via trigger: data_fim_semana + prazo_edicao_config()
  "gerado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "relatorios_diarios" (
  "id_relatorio_diario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "relatorio_semanal_id" Int NOT NULL,
  "usuario_id" Int NOT NULL,
  "data_referencia" TIMESTAMP NOT NULL,
  "eva_dor" Int,
  "fadiga_percebida" Int,
  "observacoes" TEXT,
  "turno" turno_dia NOT NULL,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  -- tmb tem que ter os minutos por intensidade, mas isso é atualizado via trigger toda vez que um registro de atividade é inserido/atualizado/excluído
  "minutos_leve" Int NOT NULL DEFAULT 0,
  "minutos_moderado" Int NOT NULL DEFAULT 0,
  "minutos_intenso" Int NOT NULL DEFAULT 0,
  "pontuacao" Int NOT NULL DEFAULT 0 -- Calculado como: (minutos_leve * 1) + (minutos_moderado * 2) + (minutos_intenso * 3)
);

CREATE TABLE "registros_atividade" (
  "id_registro_atividade" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "relatorio_diario_id" Int NOT NULL,
  "atividade_cadastrada_id" Int NOT NULL,
  "duracao_minutos" Int NOT NULL,
  "intensidade_percebida" intensidade_atividade NOT NULL,
  "resultado_met" Decimal NOT NULL,
  "realizada_em" TIMESTAMP NOT NULL,
  "editavel_ate" TIMESTAMP NOT NULL DEFAULT (now() + prazo_edicao_config()),
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "metas_semanais" (
  "id_meta_semanal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "meta_minutos" Int NOT NULL DEFAULT 150,
  "data_inicio_semana" TIMESTAMP NOT NULL,
  "notificacoes_ativas" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "lembretes" (
  "id_lembrete" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "mensagem" TEXT NOT NULL,
  "horario" TIME NOT NULL,
  "dias_da_semana" INT[], -- Array de 0-6 (Domingo-Sábado)
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "descobertas" (
  "id_descoberta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "url_imagem" TEXT CHECK (url_imagem ~* '^https?://.+$'),
  "autor_id" Int NOT NULL,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "notificacoes" (
  "id_notificacao" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "tipo" TEXT NOT NULL,
  "titulo" TEXT NOT NULL,
  "mensagem" TEXT NOT NULL,
  "lida_em" TIMESTAMP,
  "enviada_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "atividades_cadastradas" ("nome", "intensidade_padrao");

CREATE UNIQUE INDEX ON "relatorios_semanais" ("usuario_id", "data_inicio_semana");

CREATE UNIQUE INDEX ON "relatorios_diarios" ("usuario_id", "data_referencia");

CREATE UNIQUE INDEX ON "sessoes_triagem" ("usuario_id", "fase") WHERE ativa = true;

CREATE UNIQUE INDEX ON "metas_semanais" ("usuario_id", "data_inicio_semana");

COMMENT ON COLUMN "usuarios"."nome" IS 'RF1';

COMMENT ON COLUMN "usuarios"."email" IS 'RF1';

COMMENT ON COLUMN "usuarios"."telefone" IS 'RF1';

COMMENT ON COLUMN "usuarios"."data_nascimento" IS 'RF1';

COMMENT ON COLUMN "usuarios"."senha_hash" IS 'RF5 - Alfanumérica. Null se login via Google';

COMMENT ON COLUMN "usuarios"."google_id" IS 'RF6 - ID provedor Google';

COMMENT ON COLUMN "usuarios"."email_verificado" IS 'RF9';

COMMENT ON COLUMN "usuarios"."lgpd_aceita_em" IS 'RF7';

COMMENT ON COLUMN "usuarios"."consentimento_saude_em" IS 'RF8';

COMMENT ON COLUMN "usuarios"."ativo" IS 'RF41';

COMMENT ON COLUMN "perfis_paciente"."sexo" IS 'RF2';

COMMENT ON COLUMN "perfis_paciente"."escolaridade" IS 'RF2';

COMMENT ON COLUMN "perfis_paciente"."raca_cor" IS 'RF2';

COMMENT ON COLUMN "perfis_paciente"."estado_civil" IS 'RF2';

COMMENT ON COLUMN "perfis_paciente"."tipo_artrite_id" IS 'RF3';

COMMENT ON COLUMN "perfis_paciente"."tempo_tratamento_meses" IS 'RF4 - Opcional';

COMMENT ON COLUMN "perfis_paciente"."tempo_diagnostico_meses" IS 'RF4 - Opcional';

COMMENT ON COLUMN "tipos_artrite"."nome" IS 'RF3/RF43 - Ex: Reumatoide, Psoriásica, Espondiloartrite';

COMMENT ON COLUMN "sessoes_triagem"."fase" IS 'RF18 - Início ou fim do período de teste';

COMMENT ON COLUMN "sessoes_triagem"."score_ipaq" IS 'RF15 - IPAQ curto';

COMMENT ON COLUMN "sessoes_triagem"."score_facit_f" IS 'RF15 - FACIT-F';

COMMENT ON COLUMN "sessoes_triagem"."score_pam13" IS 'RF15 - PAM-13';

COMMENT ON COLUMN "sessoes_triagem"."score_sam" IS 'RF15 - SAM';

COMMENT ON COLUMN "sessoes_triagem"."score_sure" IS 'RF15 - SURE';

COMMENT ON COLUMN "sessoes_triagem"."score_umars" IS 'RF15 - uMARS';

COMMENT ON COLUMN "sessoes_triagem"."score_eheals" IS 'RF15 - eHEALS';

COMMENT ON COLUMN "sessoes_triagem"."eva_inicial" IS 'RF15/RF16 - EVA dor (0-10)';

COMMENT ON COLUMN "sessoes_triagem"."respostas_brutas" IS 'JSONB - backup das respostas por instrumento';

COMMENT ON COLUMN "atividades_cadastradas"."nome" IS 'Ex: Caminhada, Ciclismo, Limpar casa';
COMMENT ON COLUMN "atividades_cadastradas"."valor_met" IS 'Valor MET conforme Compêndio';

COMMENT ON COLUMN "relatorios_semanais"."minutos_leve" IS 'Pergunta 9/10';

COMMENT ON COLUMN "relatorios_semanais"."editavel_ate" IS 'RF22/Pergunta 4 - 3 dias após fim da semana';

COMMENT ON COLUMN "relatorios_diarios"."turno" IS 'RF28/RF29 - Manhã ou Noite';

COMMENT ON COLUMN "relatorios_diarios"."eva_dor" IS 'EVA 0-10';

COMMENT ON COLUMN "relatorios_diarios"."fadiga_percebida" IS 'Escala a definir';

COMMENT ON COLUMN "relatorios_diarios"."observacoes" IS 'Observações livres do paciente';

COMMENT ON COLUMN "registros_atividade"."duracao_minutos" IS 'RF19';

COMMENT ON COLUMN "registros_atividade"."intensidade_percebida" IS 'RF19';

COMMENT ON COLUMN "registros_atividade"."resultado_met" IS 'RF20 - MET * (duração/60)';

COMMENT ON COLUMN "registros_atividade"."realizada_em" IS 'Quando a atividade foi realizada';

COMMENT ON COLUMN "registros_atividade"."editavel_ate" IS 'RF22 - 72h após criação';

COMMENT ON COLUMN "metas_semanais"."meta_minutos" IS 'RF24 - Padrão 150 min OMS';

COMMENT ON COLUMN "metas_semanais"."notificacoes_ativas" IS 'RF26';

COMMENT ON COLUMN "lembretes"."mensagem" IS 'RF27';

COMMENT ON COLUMN "lembretes"."horario" IS 'HH:MM';

COMMENT ON COLUMN "lembretes"."dias_da_semana" IS 'Pendente Pergunta 16';

COMMENT ON COLUMN "descobertas"."titulo" IS 'RF38';

COMMENT ON COLUMN "descobertas"."url_imagem" IS 'Pendente Pergunta 31';

COMMENT ON COLUMN "descobertas"."autor_id" IS 'Admin que criou';

COMMENT ON COLUMN "notificacoes"."tipo" IS 'RELATORIO_MANHA, RELATORIO_NOITE, LEMBRETE_META, INATIVIDADE';

ALTER TABLE "perfis_paciente" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfis_paciente" ADD FOREIGN KEY ("tipo_artrite_id") REFERENCES "tipos_artrite" ("id_tipo_artrite") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessoes_triagem" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "relatorios_semanais" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "relatorios_diarios" ADD FOREIGN KEY ("relatorio_semanal_id") REFERENCES "relatorios_semanais" ("id_relatorio_semanal") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "relatorios_diarios" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "registros_atividade" ADD FOREIGN KEY ("relatorio_diario_id") REFERENCES "relatorios_diarios" ("id_relatorio_diario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "registros_atividade" ADD FOREIGN KEY ("atividade_cadastrada_id") REFERENCES "atividades_cadastradas" ("id_atividade_cadastrada") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "metas_semanais" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lembretes" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "descobertas" ADD FOREIGN KEY ("autor_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacoes" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

-- Índices para FKs (Melhoria de Performance)
CREATE INDEX ON "relatorios_semanais" ("usuario_id");
CREATE INDEX ON "relatorios_diarios" ("usuario_id");
CREATE INDEX ON "relatorios_diarios" ("relatorio_semanal_id");
CREATE INDEX ON "registros_atividade" ("relatorio_diario_id");
CREATE INDEX ON "sessoes_triagem" ("usuario_id");
CREATE INDEX ON "notificacoes" ("usuario_id");

-- Trigger para automatizar o cálculo de 'editavel_ate' em relatórios semanais
CREATE OR REPLACE FUNCTION set_editavel_ate_semanal() 
RETURNS trigger AS $$
BEGIN
  NEW.editavel_ate := NEW.data_fim_semana + prazo_edicao_config();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_editavel_ate_semanal
BEFORE INSERT OR UPDATE OF data_fim_semana ON "relatorios_semanais"
FOR EACH ROW EXECUTE FUNCTION set_editavel_ate_semanal();

-- NOTA: A lógica de 'meta_atingida' deve ser implementada via trigger na tabela 'registros_atividade'
-- ou via aplicação, cruzando 'relatorios_semanais.minutos_totais' com 'metas_semanais.meta_minutos'.
COMMENT ON COLUMN "relatorios_semanais"."meta_atingida" IS 'Calculado dinamicamente via trigger baseado nos minutos ativos da semana';
