/*
  SISTEMA DE MONITORAMENTO DE ATIVIDADE FÍSICA - SCHEMA SIMPLIFICADO (SINGULAR)
  Versão: Consolidação de Relatórios e Notificações Externas.
*/

-- 1. Definição de Tipos Enumerados
CREATE TYPE "papel_usuario" AS ENUM (
  'PACIENTE',
  'ADMINISTRADOR'
);

CREATE TYPE "fase_triagem" AS ENUM (
  'INICIAL',
  'FINAL'
);

CREATE TYPE "intensidade_atividade" AS ENUM (
  'LEVE',
  'MODERADO',
  'INTENSO'
);

CREATE TYPE "turno_dia" AS ENUM (
  'MANHA',
  'NOITE'
);

-- 2. Configurações Globais
CREATE OR REPLACE FUNCTION prazo_edicao_config() RETURNS interval AS $$
BEGIN
  RETURN interval '72 hours';
END;
$$ LANGUAGE plpgsql;

-- 3. Tabelas de Identidade e Perfis
CREATE TABLE "usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "telefone" TEXT NOT NULL,
  "data_nascimento" DATE NOT NULL,
  "senha_hash" TEXT,
  "google_id" TEXT UNIQUE,
  "papel" papel_usuario NOT NULL DEFAULT 'PACIENTE',
  "email_verificado" Boolean NOT NULL DEFAULT false,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "tipo_artrite" (
  "id_tipo_artrite" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT UNIQUE NOT NULL,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "perfil_paciente" (
  "id_perfil_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int UNIQUE NOT NULL,
  "sexo" TEXT NOT NULL,
  "escolaridade" TEXT NOT NULL,
  "raca_cor" TEXT NOT NULL,
  "estado_civil" TEXT NOT NULL,
  "tipo_artrite_id" Int NOT NULL,
  "tempo_tratamento_meses" Int,
  "tempo_diagnostico_meses" Int,
  -- Colunas movidas da tabela usuario
  "lgpd_aceita_em" TIMESTAMP,
  "consentimento_saude_em" TIMESTAMP,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario"),
  FOREIGN KEY ("tipo_artrite_id") REFERENCES "tipo_artrite" ("id_tipo_artrite")
);

-- 4. Avaliação Clínica
CREATE TABLE "sessao_triagem" (
  "id_sessao_triagem" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "fase" fase_triagem NOT NULL,
  "score_ipaq" Decimal,
  "score_facit_f" Decimal,
  "score_pam13" Decimal,
  "score_sam" Decimal,
  "score_sure" Decimal,
  "score_umars" Decimal,
  "score_eheals" Decimal,
  "respostas_brutas" Json,
  "concluida_em" TIMESTAMP,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "ativa" Boolean NOT NULL DEFAULT true,
  FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario")
);

-- 5. Monitoramento de Atividade
CREATE TABLE "atividade_cadastrada" (
  "id_atividade_cadastrada" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "categoria" TEXT,
  "MET_leve" FLOAT NOT NULL,
  "MET_moderado" FLOAT NOT NULL,
  "MET_intenso" FLOAT NOT NULL,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "relatorio" (
  "id_relatorio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "data_referencia" DATE NOT NULL,
  "turno" turno_dia NOT NULL,
  "fadiga_percebida" Int,
  "observacoes" TEXT,
  "minutos_leve" Int NOT NULL DEFAULT 0,
  "minutos_moderado" Int NOT NULL DEFAULT 0,
  "minutos_intenso" Int NOT NULL DEFAULT 0,
  "pontuacao" Int NOT NULL DEFAULT 0,
  "met_total" Decimal NOT NULL DEFAULT 0,
  "eva_media" Int CHECK ("eva_media" >= 0 AND "eva_media" <= 10),
  "editavel_ate" TIMESTAMP NOT NULL,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario"),
  UNIQUE ("usuario_id", "data_referencia", "turno")
);

CREATE TABLE "registro_atividade" (
  "id_registro_atividade" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "relatorio_id" Int NOT NULL,
  "atividade_cadastrada_id" Int NOT NULL,
  "duracao_minutos" Int NOT NULL,
  "intensidade_percebida" intensidade_atividade NOT NULL,
  "resultado_met" Decimal NOT NULL,
  "realizada_em" TIMESTAMP NOT NULL,
  "eva_dor" Int CHECK ("eva_dor" >= 0 AND "eva_dor" <= 10),
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  FOREIGN KEY ("relatorio_id") REFERENCES "relatorio" ("id_relatorio"),
  FOREIGN KEY ("atividade_cadastrada_id") REFERENCES "atividade_cadastrada" ("id_atividade_cadastrada")
);

-- 6. Engajamento e Conteúdo
CREATE TABLE "meta_semanal" (
  "id_meta_semanal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "meta_minutos" Int NOT NULL DEFAULT 150,
  "data_inicio_semana" DATE NOT NULL,
  "notificacoes_ativas" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario"),
  UNIQUE ("usuario_id", "data_inicio_semana")
);

/* REVISÃO: Lembretes e Notificações unificados em Notificação Externa 
   focado no agendamento de disparos para o usuário.
*/
CREATE TABLE "notificacao_externa" (
  "id_notificacao_externa" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" Int NOT NULL,
  "mensagem_padrao" TEXT NOT NULL,
  "horario_disparo" TIME NOT NULL,
  "dias_da_semana" INT[], -- Array de inteiros (0-6) para representar os dias
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario")
);

CREATE TABLE "descoberta" (
  "id_descoberta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "url_imagem" TEXT,
  "autor_id" Int NOT NULL,
  "ativo" Boolean NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  FOREIGN KEY ("autor_id") REFERENCES "usuario" ("id_usuario")
);

-- 7. Índices para Performance
CREATE INDEX ON "relatorio" ("usuario_id", "data_referencia");
CREATE INDEX ON "registro_atividade" ("relatorio_id");
CREATE INDEX ON "sessao_triagem" ("usuario_id");
CREATE INDEX ON "notificacao_externa" ("usuario_id");

-- 8. Automação (Trigger)
CREATE OR REPLACE FUNCTION set_editavel_ate_relatorio() 
RETURNS trigger AS $$
BEGIN
  NEW.editavel_ate := now() + prazo_edicao_config();
  RETURN NEW;
END;
$$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_editavel_ate_relatorio
BEFORE INSERT ON "relatorio"
FOR EACH ROW EXECUTE FUNCTION set_editavel_ate_relatorio();

CREATE OR REPLACE VIEW view_progresso_semanal AS
SELECT 
    usuario_id,
    DATE_TRUNC('week', data_referencia)::DATE AS data_inicio_semana,
    SUM(minutos_leve) AS total_minutos_leve,
    SUM(minutos_moderado) AS total_minutos_moderado,
    SUM(minutos_intenso) AS total_minutos_intenso,
    SUM(minutos_leve + minutos_moderado + minutos_intenso) AS total_minutos_geral,
    ROUND(AVG(eva_dor), 1) AS media_dor,
    ROUND(AVG(fadiga_percebida), 1) AS media_fadiga,
    SUM(pontuacao) AS pontuacao_total_semana,
    SUM(met_total) AS met_total_semana,
    COUNT(DISTINCT data_referencia) AS dias_com_registro
FROM "relatorio"
GROUP BY usuario_id, DATE_TRUNC('week', data_referencia);