/*
  VIVASSO - Schema do Banco de Dados (v0.7)
  
  Hierarquia de monitoramento:
    relatorio (diário, por turno) → registro_atividade
    Agregação semanal via VIEW (view_progresso_semanal)

    TABELAS → triagem_ipaq, triagem_eheals, triagem_pam13, SAM, SURE, uMARS, FACIT-F (aguardando casos de uso)

  Regra de edição: centralizada em prazo_edicao_config() (72h)
*/

-- 1. Enums

CREATE TYPE "papel_usuario" AS ENUM (
  'PACIENTE',
  'ADMINISTRADOR'
);

CREATE TYPE "intensidade_atividade" AS ENUM (
  'LEVE',
  'MODERADO',
  'INTENSO'
);

-- 2. Configuração global

CREATE OR REPLACE FUNCTION prazo_edicao_config() RETURNS interval AS $$
BEGIN
  RETURN interval '72 hours';
END;
$$ LANGUAGE plpgsql;

-- 3. Identidade e perfis

CREATE TABLE "usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "telefone" TEXT NOT NULL,
  "data_nascimento" DATE NOT NULL,
  "senha_hash" TEXT,
  "google_id" TEXT UNIQUE,
  "papel" papel_usuario NOT NULL DEFAULT 'PACIENTE',
  "email_verificado" BOOLEAN NOT NULL DEFAULT false,
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "tipo_artrite" (
  "id_tipo_artrite" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT UNIQUE NOT NULL,
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "perfil_paciente" (
  "id_perfil_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" INT UNIQUE NOT NULL,
  "sexo" TEXT NOT NULL,
  "escolaridade" TEXT NOT NULL,
  "raca_cor" TEXT NOT NULL,
  "estado_civil" TEXT NOT NULL,
  "tipo_artrite_id" INT NOT NULL,
  "tempo_tratamento_meses" INT,
  "tempo_diagnostico_meses" INT,
  "lgpd_aceita_em" TIMESTAMP,
  "consentimento_saude_em" TIMESTAMP,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

-- 4. Triagem

CREATE TABLE "sessao_triagem" (
  "id_sessao_triagem" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" INT NOT NULL,
  "numeracao_triagem" SERIAl NOT NULL,
  "concluida_em" TIMESTAMP,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "ativa" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "triagem_ipaq" (
  "id_triagem_ipaq" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessao_triagem_id" INT UNIQUE NOT NULL,

  "trabalho_remunerado" BOOLEAN NOT NULL,
  "horas_trabalho_dia" INT,
  "anos_estudo" INT NOT NULL,
  "autopercepcao_saude" INT NOT NULL CHECK ("autopercepcao_saude" BETWEEN 1 AND 5),

  "vigorosa_dias" INT NOT NULL CHECK ("vigorosa_dias" BETWEEN 0 AND 7),
  "vigorosa_minutos" INT NOT NULL DEFAULT 0,

  "moderada_dias" INT NOT NULL CHECK ("moderada_dias" BETWEEN 0 AND 7),
  "moderada_minutos" INT NOT NULL DEFAULT 0,

  "caminhada_dias" INT NOT NULL CHECK ("caminhada_dias" BETWEEN 0 AND 7),
  "caminhada_minutos" INT NOT NULL DEFAULT 0,

  "sentado_semana_minutos" INT NOT NULL DEFAULT 0,
  "sentado_fds_minutos" INT NOT NULL DEFAULT 0,

  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "triagem_eheals" (
  "id_triagem_eheals" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessao_triagem_id" INT UNIQUE NOT NULL,

  "q1_recursos_disponiveis" INT NOT NULL CHECK ("q1_recursos_disponiveis" BETWEEN 1 AND 5),
  "q2_onde_encontrar" INT NOT NULL CHECK ("q2_onde_encontrar" BETWEEN 1 AND 5),
  "q3_como_encontrar" INT NOT NULL CHECK ("q3_como_encontrar" BETWEEN 1 AND 5),
  "q4_esclarecer_duvidas" INT NOT NULL CHECK ("q4_esclarecer_duvidas" BETWEEN 1 AND 5),
  "q5_usar_informacoes" INT NOT NULL CHECK ("q5_usar_informacoes" BETWEEN 1 AND 5),
  "q6_avaliar_recursos" INT NOT NULL CHECK ("q6_avaliar_recursos" BETWEEN 1 AND 5),
  "q7_diferenciar_qualidade" INT NOT NULL CHECK ("q7_diferenciar_qualidade" BETWEEN 1 AND 5),
  "q8_seguranca_decisoes" INT NOT NULL CHECK ("q8_seguranca_decisoes" BETWEEN 1 AND 5),

  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "triagem_pam13" (
  "id_triagem_pam13" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessao_triagem_id" INT UNIQUE NOT NULL,

  "q1_responsavel_saude" INT CHECK ("q1_responsavel_saude" BETWEEN 1 AND 4),
  "q2_participacao_ativa" INT CHECK ("q2_participacao_ativa" BETWEEN 1 AND 4),
  "q3_confianca_prevenir" INT CHECK ("q3_confianca_prevenir" BETWEEN 1 AND 4),
  "q4_medicamentos" INT CHECK ("q4_medicamentos" BETWEEN 1 AND 4),
  "q5_quando_ir_medico" INT CHECK ("q5_quando_ir_medico" BETWEEN 1 AND 4),
  "q6_contar_preocupacoes" INT CHECK ("q6_contar_preocupacoes" BETWEEN 1 AND 4),
  "q7_seguir_tratamentos" INT CHECK ("q7_seguir_tratamentos" BETWEEN 1 AND 4),
  "q8_entender_problemas" INT CHECK ("q8_entender_problemas" BETWEEN 1 AND 4),
  "q9_tratamentos_disponiveis" INT CHECK ("q9_tratamentos_disponiveis" BETWEEN 1 AND 4),
  "q10_manter_mudancas" INT CHECK ("q10_manter_mudancas" BETWEEN 1 AND 4),
  "q11_prevenir_problemas" INT CHECK ("q11_prevenir_problemas" BETWEEN 1 AND 4),
  "q12_encontrar_solucoes" INT CHECK ("q12_encontrar_solucoes" BETWEEN 1 AND 4),
  "q13_manter_sob_estresse" INT CHECK ("q13_manter_sob_estresse" BETWEEN 1 AND 4),

  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

-- 5. Monitoramento de atividade

CREATE TABLE "categoria_atividade" (
  id_categoria_atividade INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "atividade_cadastrada" (
  "id_atividade_cadastrada" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "categoria" INT NOT NULL,
  "MET_leve" FLOAT NOT NULL,
  "MET_moderado" FLOAT NOT NULL,
  "MET_intenso" FLOAT NOT NULL,
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now())
);



CREATE TABLE "relatorio" (
  "id_relatorio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" INT NOT NULL,
  "data_referencia" DATE NOT NULL,
  "eva_dor" INT CHECK ("eva_dor" >= 0 AND "eva_dor" <= 10),
  "fadiga_percebida" INT,
  "observacoes" TEXT,
  "minutos_leve" INT NOT NULL DEFAULT 0,
  "minutos_moderado" INT NOT NULL DEFAULT 0,
  "minutos_intenso" INT NOT NULL DEFAULT 0,
  "pontuacao" INT NOT NULL DEFAULT 0,
  "met_total" DECIMAL NOT NULL DEFAULT 0,
  "editavel_ate" TIMESTAMP NOT NULL,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "registro_atividade" (
  "id_registro_atividade" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "relatorio_id" INT NOT NULL,
  "atividade_cadastrada_id" INT NOT NULL,
  "duracao_minutos" INT NOT NULL,
  "intensidade_percebida" intensidade_atividade NOT NULL,
  "resultado_met" DECIMAL NOT NULL,
  "realizada_em" TIMESTAMP NOT NULL,
  "eva_dor" INT CHECK ("eva_dor" >= 0 AND "eva_dor" <= 10),
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);


-- 6. Metas

CREATE TABLE "meta_semanal" (
  "id_meta_semanal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" INT NOT NULL,
  "meta_minutos" INT NOT NULL DEFAULT 150,
  "data_inicio_semana" DATE NOT NULL,
  "notificacoes_ativas" BOOLEAN NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

-- 7. Notificações externas

CREATE TABLE "notificacao_externa" (
  "id_notificacao_externa" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" INT NOT NULL,
  "mensagem_padrao" TEXT NOT NULL,
  "horario_disparo" TIME NOT NULL,
  "dias_da_semana" INT[],
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

-- 8. Descobertas

CREATE TABLE "descoberta" (
  "id_descoberta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "url_imagem" TEXT,
  "autor_id" INT NOT NULL,
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "criado_em" TIMESTAMP NOT NULL DEFAULT (now()),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT (now())
);

-- 9. Monitoramento de Fadiga (FACIT-F) - Conectado ao Relatório

CREATE TABLE "monitoramento_facit_f" (
  "id_facit" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_relatorio" INT NOT NULL REFERENCES "relatorio" ("id_relatorio"),
  "criado_em" TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- 13 itens da escala de fadiga (0 a 4)
  "item_1" INT NOT NULL, "item_2" INT NOT NULL, "item_3" INT NOT NULL,
  "item_4" INT NOT NULL, "item_5" INT NOT NULL, "item_6" INT NOT NULL,
  "item_7" INT NOT NULL, "item_8" INT NOT NULL, "item_9" INT NOT NULL,
  "item_10" INT NOT NULL, "item_11" INT NOT NULL, "item_12" INT NOT NULL,
  "item_13" INT NOT NULL,
  "escore_total" INT
);

-- 10. Feedback e Avaliação (SURE, uMARS, SAM) - Conectado ao Paciente (Usuário)

CREATE TABLE "feedback_sure" (
  "id_sure" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INT NOT NULL REFERENCES "usuario" ("id_usuario"),
  "data_preenchimento" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "p1" INT, "p2" INT, "p3" INT, "p4" INT, "p5" INT, "p6" INT, "p7" INT, "p8" INT
);

CREATE TABLE "feedback_umars" (
  "id_umars" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INT NOT NULL REFERENCES "usuario" ("id_usuario"),
  "data_preenchimento" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "engajamento_1" INT, "engajamento_2" INT, "engajamento_3" INT, "engajamento_4" INT, "engajamento_5" INT,
  "funcionalidade_6" INT, "funcionalidade_7" INT, "funcionalidade_8" INT, "funcionalidade_9" INT,
  "estetica_10" INT, "estetica_11" INT, "estetica_12" INT,
  "informacao_13" INT, "informacao_14" INT, "informacao_15" INT, "informacao_16" INT, "informacao_17" INT,
  "subjetiva_18" INT, "subjetiva_19" INT, "subjetiva_20" INT, "subjetiva_21" INT,
  "percepcao_22" INT, "percepcao_23" INT, "percepcao_24" INT, "percepcao_25" INT, "percepcao_26" INT
);

CREATE TABLE "feedback_sam" (
  "id_sam" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" INT NOT NULL REFERENCES "usuario" ("id_usuario"),
  "data_preenchimento" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "conteudo_1" INT, "conteudo_2" INT, "conteudo_3" INT,
  "linguagem_4" INT, "linguagem_5" INT, "linguagem_6" INT, "linguagem_7" INT,
  "ilustracoes_8" INT, "ilustracoes_9" INT, "ilustracoes_10" INT, "ilustracoes_11" INT,
  "layout_12" INT, "layout_13" INT, "layout_14" INT,
  "estimulacao_15" INT, "estimulacao_16" INT, "estimulacao_17" INT,
  "cultural_18" INT, "cultural_19" INT, "cultural_20" INT, "cultural_21" INT, "cultural_22" INT
);

-- 9. Foreign keys

ALTER TABLE "perfil_paciente" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario");
ALTER TABLE "perfil_paciente" ADD FOREIGN KEY ("tipo_artrite_id") REFERENCES "tipo_artrite" ("id_tipo_artrite");

ALTER TABLE "sessao_triagem" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario");
ALTER TABLE "triagem_ipaq" ADD FOREIGN KEY ("sessao_triagem_id") REFERENCES "sessao_triagem" ("id_sessao_triagem");
ALTER TABLE "triagem_eheals" ADD FOREIGN KEY ("sessao_triagem_id") REFERENCES "sessao_triagem" ("id_sessao_triagem");
ALTER TABLE "triagem_pam13" ADD FOREIGN KEY ("sessao_triagem_id") REFERENCES "sessao_triagem" ("id_sessao_triagem");

ALTER TABLE "relatorio" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario");
ALTER TABLE "registro_atividade" ADD FOREIGN KEY ("relatorio_id") REFERENCES "relatorio" ("id_relatorio");
ALTER TABLE "registro_atividade" ADD FOREIGN KEY ("atividade_cadastrada_id") REFERENCES "atividade_cadastrada" ("id_atividade_cadastrada");
ALTER TABLE "atividade_cadastrada" ADD FOREIGN KEY ("categoria") REFERENCES "categoria_atividade" ("id_categoria_atividade");


ALTER TABLE "meta_semanal" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario");
ALTER TABLE "notificacao_externa" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario");
ALTER TABLE "descoberta" ADD FOREIGN KEY ("autor_id") REFERENCES "usuario" ("id_usuario");

-- 10. Índices únicos compostos
CREATE UNIQUE INDEX ON "meta_semanal" ("usuario_id", "data_inicio_semana");

-- 11. Índices de performance

CREATE INDEX ON "relatorio" ("usuario_id", "data_referencia");
CREATE INDEX ON "registro_atividade" ("relatorio_id");
CREATE INDEX ON "sessao_triagem" ("usuario_id");
CREATE INDEX ON "notificacao_externa" ("usuario_id");

-- 12. Triggers

CREATE OR REPLACE FUNCTION set_editavel_ate_relatorio()
RETURNS trigger AS $$
BEGIN
  NEW.editavel_ate := now() + prazo_edicao_config();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_editavel_ate_relatorio
BEFORE INSERT ON "relatorio"
FOR EACH ROW EXECUTE FUNCTION set_editavel_ate_relatorio();

-- 13. View de progresso semanal

CREATE OR REPLACE VIEW view_progresso_semanal AS
SELECT
    usuario_id,
    DATE_TRUNC('week', data_referencia)::DATE AS data_inicio_semana,
    SUM(minutos_leve) AS total_minutos_leve,
    SUM(minutos_moderado) AS total_minutos_moderado,
    SUM(minutos_intenso) AS total_minutos_intenso,
    SUM(minutos_leve + minutos_moderado + minutos_intenso) AS total_minutos_geral,
    ROUND(AVG(eva_dor), 1) AS media_dor,
    ROUND(AVG(fadiga_percebida), 1) AS media_fadiga,
    SUM(pontuacao) AS pontuacao_total_semana,
    SUM(met_total) AS met_total_semana,
    COUNT(DISTINCT data_referencia) AS dias_com_registro
FROM "relatorio"
GROUP BY usuario_id, DATE_TRUNC('week', data_referencia);


/*
-- 14. Comentários de rastreabilidade

COMMENT ON COLUMN "usuario"."nome" IS 'RF1';
COMMENT ON COLUMN "usuario"."email" IS 'RF1, RF11, RF13';
COMMENT ON COLUMN "usuario"."telefone" IS 'RF1';
COMMENT ON COLUMN "usuario"."data_nascimento" IS 'RF1 - Idade derivada no código';
COMMENT ON COLUMN "usuario"."senha_hash" IS 'RF5 - Alfanumérica. Null se login via Google';
COMMENT ON COLUMN "usuario"."google_id" IS 'RF6, RF12';
COMMENT ON COLUMN "usuario"."email_verificado" IS 'RF9';
COMMENT ON COLUMN "usuario"."ativo" IS 'RF41';

COMMENT ON COLUMN "perfil_paciente"."sexo" IS 'RF2';
COMMENT ON COLUMN "perfil_paciente"."escolaridade" IS 'RF2';
COMMENT ON COLUMN "perfil_paciente"."raca_cor" IS 'RF2';
COMMENT ON COLUMN "perfil_paciente"."estado_civil" IS 'RF2';
COMMENT ON COLUMN "perfil_paciente"."tipo_artrite_id" IS 'RF3';
COMMENT ON COLUMN "perfil_paciente"."tempo_tratamento_meses" IS 'RF4 - Opcional';
COMMENT ON COLUMN "perfil_paciente"."tempo_diagnostico_meses" IS 'RF4 - Opcional';
COMMENT ON COLUMN "perfil_paciente"."lgpd_aceita_em" IS 'RF7';
COMMENT ON COLUMN "perfil_paciente"."consentimento_saude_em" IS 'RF8';

COMMENT ON COLUMN "tipo_artrite"."nome" IS 'RF3/RF43';

COMMENT ON COLUMN "sessao_triagem"."fase" IS 'RF18';
COMMENT ON TABLE "triagem_ipaq" IS 'RF15 - IPAQ curto com perfil sociodemográfico';
COMMENT ON TABLE "triagem_eheals" IS 'RF15 - eHEALS, Likert 1-5';
COMMENT ON TABLE "triagem_pam13" IS 'RF15 - PAM-13, Likert 1-4 com N/A';

COMMENT ON COLUMN "relatorio"."turno" IS 'RF28/RF29';
COMMENT ON COLUMN "relatorio"."editavel_ate" IS 'RF22/Pergunta 4 - Via trigger 72h';
COMMENT ON COLUMN "relatorio"."minutos_leve" IS 'Pergunta 9/10';

COMMENT ON COLUMN "registro_atividade"."duracao_minutos" IS 'RF19';
COMMENT ON COLUMN "registro_atividade"."intensidade_percebida" IS 'RF19';
COMMENT ON COLUMN "registro_atividade"."resultado_met" IS 'RF20';
COMMENT ON COLUMN "registro_atividade"."realizada_em" IS 'RF21 - Para ordenação de registros anteriores';

COMMENT ON COLUMN "meta_semanal"."meta_minutos" IS 'RF24 - Padrão 150 min OMS';
COMMENT ON COLUMN "meta_semanal"."notificacoes_ativas" IS 'RF26';

COMMENT ON COLUMN "notificacao_externa"."mensagem_padrao" IS 'RF27';
COMMENT ON COLUMN "notificacao_externa"."horario_disparo" IS 'RF29 - 20h padrão';

COMMENT ON COLUMN "descoberta"."titulo" IS 'RF38';
*/

-- Fim do Arquivo